### ISSUE TITLE
Raising Transport

### ISSUE THREAD

**Issue by U-lis** [planetarium/NineChronicles.IAP#138]
```
[ERROR] TransportQueryError: {'message': "Error trying to resolve field 'unloadFromMyGarages'.", 'locations': [{'line': 7, 'column': 5}], 'path': ['actionTxQuery', 'unloadFromMyGarages'], 'extensions': {'code': 'ARGUMENT_OUT_OF_RANGE', 'codes': ['ARGUMENT_OUT_OF_RANGE']}}
Traceback (most recent call last):
  File "/var/task/handler.py", line 138, in handle
    (success, msg, tx_id), nonce = process(sess, record, nonce=nonce)
  File "/var/task/handler.py", line 99, in process
    unsigned_tx = gql.create_action(
  File "/var/task/common/_graphql.py", line 118, in create_action
    return fn(pubkey, nonce, **kwargs)
  File "/var/task/common/_graphql.py", line 80, in _unload_from_garage
    result = self.execute(query)
  File "/var/task/common/_graphql.py", line 27, in execute
    return sess.execute(query)
  File "/opt/python/lib/python3.10/site-packages/gql/client.py", line 860, in execute
    raise TransportQueryError(
```
is raised when we deployed 0.7.0 to mainnet.
I have no idea why this happens even if I didn't touch related code.

**Comment by U-lis** [comment]
This is because wrong message is sent to SQS by false code indentation.
This is fixed from https://github.com/planetarium/NineChronicles.IAP/pull/144
